name: "Set Issue Label and Assignee"
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: Naturalclar/issue-action@f229cda
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          title-or-body: "title"
          parameters: >
            [
            {"keywords":["yarn upgrade","upgrade yarn"],"labels":["yarn/upgrade"],"assignees":["pahud"]},
            {"keywords":["projen upgrade","upgrade projen"],"labels":["projen/upgrade"],"assignees":["pahud"]}
            ]
          
